export default {
  region: `Floating Islands`,
  levels: [
    /*------------------------------------------------------------------------------
    -----Normal Mode levels---------------------------------------------------------
    ------------------------------------------------------------------------------*/
    {
      energy: 5,
      level: 1,
      mode: `Normal`,
      lizardmanArcher: 1,
      lizardmanShaman: 1,
      wolfCub: 1,
    },
    {
      energy: 5,
      level: 2,
      mode: `Normal`,
      lizardmanArcher: 2,
      lizardmanShaman: 1,
      lizardmanWarrior: 1,
      wolfCub: 1,
    },
    {
      energy: 5,
      level: 3,
      mode: `Normal`,
      lizardmanArcher: 1,
      lizardmanShaman: 1,
      lizardmanWarrior: 1,
      wolfCub: 1,
      arcaneBird: 1,
    },
    {
      energy: 5,
      level: 4,
      mode: `Normal`,
      lizardmanArcher: 1,
      lizardmanShaman: 1,
      lizardmanWarrior: 1,
      wolfCub: 2,
      arcaneBird: 1,
      harpy: 1,
    },
    {
      energy: 5,
      level: 5,
      mode: `Normal`,
      lizardmanArcher: 2,
      lizardmanWarrior: 1,
      wolf: 3,
      arcaneEagle: 1,
    },
    {
      energy: 5,
      level: 6,
      mode: `Normal`,
      wolf: 2,
      arcaneBird: 1,
      arcaneEagle: 1,
      harpy: 3,
    },
    {
      energy: 5,
      level: 7,
      mode: `Normal`,
      silverback: 1,
      arcaneEagle: 1,
      simurgh: 1,
      harpy: 1,
      dragon: 1,
    },
    /*------------------------------------------------------------------------------
    -----Advanced mode levels-------------------------------------------------------
    ------------------------------------------------------------------------------*/
    {
      energy: 6,
      level: 1,
      mode: `Advanced`,
      lizardmanArcher: 2,
      lizardmanShaman: 2,
      wolfCub: 1,
      wolf: 2,
      arcaneEagle: 1,
    },
    {
      energy: 6,
      level: 2,
      mode: `Advanced`,
      lizardmanArcher: 2,
      lizardmanShaman: 1,
      lizardmanWarrior: 2,
      arcaneEagle: 1,
      harpy: 1,
    },
    {
      energy: 6,
      level: 3,
      mode: `Advanced`,
      lizardmanArcher: 1,
      lizardmanShaman: 1,
      lizardmanWarrior: 1,
      wolf: 3,
      silverback: 1,
      harpy: 1,
    },
    {
      energy: 6,
      level: 4,
      mode: `Advanced`,
      lizardmanArcher: 1,
      lizardmanWarrior: 2,
      wolf: 1,
      silverback: 1,
      arcaneEagle: 1,
      simurgh: 1,
      harpy: 1,
    },
    {
      energy: 6,
      level: 5,
      mode: `Advanced`,
      lizardmanArcher: 2,
      lizardmanShaman: 1,
      lizardmanWarrior: 3,
      silverback: 1,
      simurgh: 1,
    },
    {
      energy: 6,
      level: 6,
      mode: `Advanced`,
      lizardmanArcher: 1,
      lizardmanShaman: 2,
      lizardmanWarrior: 1,
      wolf: 2,
      silverback: 1,
      fury: 1,
    },
    {
      energy: 6,
      level: 7,
      mode: `Advanced`,
      lizardmanShaman: 2,
      lizardmanWarrior: 1,
      wolf: 1,
      simurgh: 1,
      harpy: 1,
      fury: 1,
      dragon: 1,
    },
    /*------------------------------------------------------------------------------
    -----Nightmare mode levels------------------------------------------------------
    ------------------------------------------------------------------------------*/
    {
      energy: 7,
      level: 1,
      mode: `Nightmare`,
      lizardmanArcher: 1,
      lizardmanShaman: 2,
      lizardmanWarrior: 1,
      wolf: 1,
      silverback: 1,
      simurgh: 1,
    },
    {
      energy: 7,
      level: 2,
      mode: `Nightmare`,
      lizardmanWarrior: 1,
      wolf: 1,
      silverback: 2,
      arcaneEagle: 1,
      harpy: 1,
      fury: 1,
    },
    {
      energy: 7,
      level: 3,
      mode: `Nightmare`,
      lizardmanArcher: 1,
      lizardmanShaman: 2,
      lizardmanWarrior: 1,
      wolf: 1,
      silverback: 1,
      simurgh: 2,
    },
    {
      energy: 7,
      level: 4,
      mode: `Nightmare`,
      lizardmanShaman: 3,
      lizardmanWarrior: 2,
      wolf: 2,
      silverback: 1,
    },
    {
      energy: 7,
      level: 5,
      mode: `Nightmare`,
      lizardmanArcher: 3,
      lizardmanShaman: 1,
      wolf: 1,
      silverback: 3,
    },
    {
      energy: 7,
      level: 6,
      mode: `Nightmare`,
      lizardmanArcher: 1,
      lizardmanShaman: 2,
      lizardmanWarrior: 1,
      wolf: 1,
      silverback: 1,
      simurgh: 1,
      fury: 1,
    },
    {
      energy: 7,
      level: 7,
      mode: `Nightmare`,
      lizardmanArcher: 1,
      lizardmanShaman: 1,
      silverback: 2,
      simurgh: 1,
      fury: 2,
      dragon: 1,
    },
  ]
}